### ISSUE TITLE
r66s重启后MAC地址会改变

### ISSUE THREAD

**Issue by tpishere** [ophub/rockchip-armbian#3]
每次断电或重启后MAC地址都会随机生成新的，希望能够固定生成MAC地址

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md

根据12.7，设置静态IP

**Comment by tpishere** [comment]
谢谢

> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md
> 
> 根据12.7，设置静态IP
