### ISSUE TITLE
rk5b spi_loader

### ISSUE THREAD

**Issue by bigmangos** [ophub/rockchip-armbian#4]
https://github.com/ophub/rockchip-armbian/tree/main/build-armbian/u-boot/rock5b

请问一下大佬，这个目录下的spi_loader有什么区别，是怎么编译的呢？

**Comment by ophub** [comment]
使用nvme的需要安装spi，其他emmc等介质的不需要，使用radxa官方的u-boot源码编译。

https://github.com/radxa/u-boot
https://github.com/radxa/rkbin
https://github.com/radxa/build

然后执行 `./build/mk-uboot.sh rk3588-rock-5b`即可
