### ISSUE TITLE
贝壳云使用构建的最新的镜像刷机后，不能正常启动获取ip

### ISSUE THREAD

**Issue by hanshantao** [ophub/rockchip-armbian#5]
贝壳云使用构建的最新的镜像刷机后，不能正常启动获取ip
尝试连接hdmi也没有信号输出，瑞芯微的刷机工具显示是成功了。

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.0.y/commit/214ac28fecc58bdad6cec93c21deb7454bc311f7

问题已经修复，我刚才重新打包了最新内核的固件，你下载这个6.0.10内核的。

**Comment by hanshantao** [comment]
可以了，已经正常刷入使用了。感谢
